import smtplib

def generate_welcome_email(name: str, email: str, role: str):

    message_content = """

    Hello, {}

    This message is being automatically generated by python script. Your email setup is working.

    Your login is {}

    You are registered as a {}.

    Respectfully,
    Dins Admin
    """.format(name, email, role)

    smtp = smtplib.SMTP('smtp.gmail.com',587)
    smtp.ehlo()
    smtp.starttls()
    smtp.ehlo()
    smtp.login('yuppiecruncher@gmail.com', 'Fuz$y83@r!')
    smtp.sendmail('yuppiecruncher@gmail.com', email, message_content)
    smtp.quit()
