"""removed requested

Revision ID: 08ee5e45f2d0
Revises: dcb4e6ed32fb
Create Date: 2019-02-12 11:38:45.179665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee5e45f2d0'
down_revision = 'dcb4e6ed32fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'requested_by_diner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('requested_by_diner', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
