"""initial revision after major UX/UI changes

Revision ID: 19a1fe3686e1
Revises: cfda3b2d5688
Create Date: 2019-03-04 17:01:49.675106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a1fe3686e1'
down_revision = 'cfda3b2d5688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
