"""Added requested_by_diner column

Revision ID: 804ce202b9fa
Revises: cc4e8e5323af
Create Date: 2019-02-12 10:54:33.980668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804ce202b9fa'
down_revision = 'cc4e8e5323af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('requested_by_diner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'requested_by_diner')
    # ### end Alembic commands ###
