"""changed datatype on id column to 'Integer' from 'BigInteger'

Revision ID: b4a31bee1caa
Revises: 4d204c3267a7
Create Date: 2019-01-11 15:05:20.294993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a31bee1caa'
down_revision = '4d204c3267a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
