"""added diner_id column in 'meals'

Revision ID: cc4e8e5323af
Revises: 8b9b35b2beeb
Create Date: 2019-01-30 10:49:26.552470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4e8e5323af'
down_revision = '8b9b35b2beeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('diner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'diner_id')
    # ### end Alembic commands ###
