"""added primary key for link table

Revision ID: cfda3b2d5688
Revises: eabfdf4cc505
Create Date: 2019-02-13 10:02:27.209919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfda3b2d5688'
down_revision = 'eabfdf4cc505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
