"""changed data type to integer

Revision ID: dcb4e6ed32fb
Revises: 804ce202b9fa
Create Date: 2019-02-12 11:36:58.871210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb4e6ed32fb'
down_revision = '804ce202b9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
