"""added linked table

Revision ID: eabfdf4cc505
Revises: 08ee5e45f2d0
Create Date: 2019-02-13 10:00:59.373955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabfdf4cc505'
down_revision = '08ee5e45f2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
